language: node_js
node_js:
  - "stable"

services:
  - postgresql

env:
  global:
  - TEST_DB_USERNAME=postgres
  - TEST_DB_NAME=Quick-Credit-Test
  - TEST_DB_HOST=127.0.0.1
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
install:
  - npm install
before_script:
  - psql -c 'drop database if exists Quick-Credit-Test;' -U postgres
  - psql -c 'create database Quick-Credit-Test;' -U postgres

script:
  - npm test
