language: node_js
node_js:
  - "stable"

services:
  - postgresql

env:
  global:
  - TEST_DB_USERNAME=quickcredit
  - TEST_DB_NAME=quickcredit_test
  - TEST_DB_HOST=127.0.0.1
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
install:
  - npm install
before_script:
  - psql -c 'create database quickcredit_test;' -U postgres
  - psql -c "CREATE USER quickcredit WITH PASSWORD null;" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test
  
after_success: 
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT